import time
import random as rand
text_time1 = rand.randint(1,3)
text_time2 = rand.randint(1,3)
text_time3 = rand.randint(1,3)
text_time4 = rand.randint(2,5)
text_time5 = rand.randint(1,4)
print("This program will read your mind!")
time.sleep(text_time1)
print("Enter a number, any number, and this program will guess it!")
time.sleep(text_time2)
number = int(input("Enter your number. Make sure it is NOT a decimal!\n"))
time.sleep(1)
print("Analyzing brainwaves...")
time.sleep(text_time3)
print("Contemplating life...")
time.sleep(text_time4)
print("Grabbing a snack...")
time.sleep(text_time5)
if number in [69, 420, 21]:
	print("Are you serious?")
	time.sleep(text_time2)
	print("Jeez kids these days are so immature.")
	time.sleep(3)
	exit()
elif number == 123:
	print("Wow, how creative.")
	time.sleep(2)
	exit()
print("The number you're thinking of is", number)
time.sleep(5)
print("This took me 5 minutes to make lol")
time.sleep(0.25)