name: Bug report
description: Report a bug
labels: ["bug"]

body:
  - type: input
    id: version
    attributes:
      label: Version
      description: The version of the game you are using.
      placeholder: Example: 1.3
    validations:
      required: true
  - type: textarea
    id: issue
    attributes:
      label: What happened?
      description: Explain the bug in detail.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      description: How you came across the issue, and what exactly you did that caused the bug.
    validations:
      required: true
   - type: checkboxes
    id: agreement
    attributes:
      label: Confirmation
      description: Check the boxes to confirm that you have read the lines below.
      options:
        - label: I have searched the closed and open issues to make sure that this problem has not already been reported.
          required: true
        - label: I have checked that the latest version still has this bug.
          required: true
