blank_issues_enabled: false
contact_links:
  - name: Support me
    url: https://patreon.com/CallMeSirEntertainment?utm_medium=clipboard_copy&utm_source=copyLink&utm_campaign=creatorshare_creator&utm_content=join_link
    about: Use this link to support me.
